# Generated by Django 4.2.17 on 2024-12-31 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='avatars/default_avatar.jpg', force_format='JPEG', keep_meta=False, quality=75, scale=None, size=[300, 300], upload_to='avatars/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
